#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Towel 2017

# https://gist.github.com/0xTowel/b4e7233fc86d8bb49698e4f1318a5a73

from math import ceil, sqrt
import sys

def bsgs(g, h, p):
    '''
    Solve for x in h = g^x mod p given a prime p.
    If p is not prime, you shouldn't use BSGS anyway.
    '''
    N = ceil(sqrt(p - 1))  # phi(p) is p-1 if p is prime

    # Store hashmap of g^{1...m} (mod p). Baby step.
    tbl = {pow(g, i, p): i for i in range(N)}

    # Precompute via Fermat's Little Theorem
    c = pow(g, N * (p - 2), p)

    # Search for an equivalence in the table. Giant step.
    for j in range(N):
        y = (h * pow(c, j, p)) % p
        if y in tbl:
            return j * N + tbl[y]

    # Solution not found
    return None


print(bsgs(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])))