#!/bin/python3
# http://www.inf.fh-flensburg.de/lang/krypto/grund/inverses-element.htm

import sys

def gcd(a, b):
    u, v, s, t = 1, 0, 0, 1
    while b!=0:
        q=a//b
        a, b = b, a-q*b
        u, s = s, u-q*s
        v, t = t, v-q*t
    return a, u, v


def modinverse(a, n):
    g, u, v =  gcd(a, n)
    return u % n

def main():
    if len(sys.argv < 2):
        print( __file__ + " <number> <modulo>")
    print (modinverse(sys.argv[1], sys.argv[2]))

if __name__ == "__main__":
    main()